// Global State & Cache
let savedFarmers = [];
let defaultPhotoSrc = 'farmer-placeholder.svg';
let cameraStreamTrack = null;
let activeView = 'dashboard';

// Filter, Sort, Pagination & Display State
const filterState = {
  search: '',
  village: 'all',
  status: 'all',
  sortBy: 'createdAt',
  sortOrder: 'desc',
  page: 1,
  limit: 10,
  totalPages: 1,
  totalRecords: 0,
  viewMode: 'grid', // 'grid' | 'table'
  availableVillages: []
};

// Debounce timer for search
let searchDebounceTimer = null;

// Translation dictionary
const marathiMap = {
  ramesh: 'रमेश', suresh: 'सुरेश', mahesh: 'महेश', ganesh: 'गणेश',
  patil: 'पाटील', deshmukh: 'देशमुख', jadhav: 'जाधव', shinde: 'शिंदे',
  kadam: 'कदम', chavan: 'चव्हाण', pawar: 'पवार', more: 'मोरे',
  gaikwad: 'गायकवाड', sonawane: 'सोनवणे', jagtap: 'जगताप', bhosale: 'भोसले'
};

function autoTranslate(text) {
  if (!text) return '';
  const words = text.toLowerCase().split(/\s+/);
  const translated = words.map((w) => marathiMap[w] || w);
  return translated.join(' ');
}

// Format and Mask Aadhaar
function formatAadhaar(value) {
  const digits = String(value || '').replace(/\D/g, '').slice(0, 12);
  if (!digits) return '';
  return digits.replace(/(\d{4})(?=\d)/g, '$1 ').trim();
}

function maskAadhaar(value) {
  const formatted = formatAadhaar(value);
  const parts = formatted.split(' ');
  if (parts.length === 3 && parts[2].length === 4) {
    return 'XXXX XXXX ' + parts[2];
  }
  return formatted ? 'XXXX XXXX ' + formatted.slice(-4).trim() : 'XXXX XXXX XXXX';
}

function handleAadhaarInput(el) {
  const formatted = formatAadhaar(el.value);
  el.value = formatted;
  toggleAadhaarMask();
}

function toggleAadhaarMask() {
  const raw = document.getElementById('aadhaarInput').value;
  const isMasked = document.getElementById('maskAadhaarCheck').checked;
  const displayEl = document.getElementById('aadhaar');

  if (!raw) {
    displayEl.innerText = 'XXXX XXXX XXXX';
    return;
  }
  displayEl.innerText = isMasked ? maskAadhaar(raw) : formatAadhaar(raw);
}

// Live Translators
function translateName(val) {
  document.getElementById('name_en').innerText = val || 'Example Name';
  const autoMr = autoTranslate(val);
  const mrInput = document.getElementById('nameMrInput');
  if (!mrInput.value || mrInput.dataset.autoGenerated === 'true') {
    mrInput.value = autoMr;
    mrInput.dataset.autoGenerated = 'true';
    document.getElementById('name_mr').innerText = autoMr || 'उदा. रमेश पाटील';
  }
}

function translateFather(val) {
  document.getElementById('father_en').innerText = val || 'Example Name';
  const autoMr = autoTranslate(val);
  const mrInput = document.getElementById('fatherMrInput');
  if (!mrInput.value || mrInput.dataset.autoGenerated === 'true') {
    mrInput.value = autoMr;
    mrInput.dataset.autoGenerated = 'true';
    document.getElementById('father_mr').innerText = autoMr || 'उदा. सुरेश पाटील';
  }
}

function getVerificationUrl(cardId) {
  const base = window.location.origin && window.location.origin !== 'null'
    ? window.location.origin
    : '';
  return `${base}/verify.html?id=${encodeURIComponent(cardId || 'KC-1001')}`;
}

function setID(val) {
  const cardId = val || 'KC-1001';
  document.getElementById('fid').innerText = cardId;
  const qrEl = document.getElementById('qr');
  if (qrEl) {
    const verifyUrl = getVerificationUrl(cardId);
    qrEl.src = `https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(verifyUrl)}`;
  }
}

function clearError(inputEl) {
  inputEl.classList.remove('input-error');
  const errBox = document.getElementById('validationErrors');
  if (errBox) errBox.innerHTML = '';
}

// Photo Handlers
function loadPhoto(event) {
  const file = event.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = function () {
    const photoEl = document.getElementById('photo');
    photoEl.src = reader.result;
    photoEl.dataset.custom = 'true';
    document.getElementById('photoName').innerText = file.name;
  };
  reader.readAsDataURL(file);
}

function resetPhoto() {
  const photoEl = document.getElementById('photo');
  photoEl.src = defaultPhotoSrc;
  delete photoEl.dataset.custom;
  document.getElementById('photoName').innerText = 'Default image selected';
  document.getElementById('photoInput').value = '';
}

// Camera Handlers
async function openCameraModal() {
  const modal = document.getElementById('cameraModal');
  const video = document.getElementById('cameraStream');
  modal.classList.add('active');

  try {
    const stream = await navigator.mediaDevices.getUserMedia({ video: { width: 640, height: 480 } });
    video.srcObject = stream;
    cameraStreamTrack = stream.getVideoTracks()[0];
  } catch (err) {
    alert('Camera access denied or unavailable: ' + err.message);
    closeCameraModal();
  }
}

function closeCameraModal() {
  const modal = document.getElementById('cameraModal');
  modal.classList.remove('active');
  if (cameraStreamTrack) {
    cameraStreamTrack.stop();
    cameraStreamTrack = null;
  }
}

function captureCameraPhoto() {
  const video = document.getElementById('cameraStream');
  const canvas = document.getElementById('cameraCanvas');
  canvas.width = video.videoWidth || 320;
  canvas.height = video.videoHeight || 320;
  const ctx = canvas.getContext('2d');
  ctx.drawImage(video, 0, 0, canvas.width, canvas.height);

  const dataUrl = canvas.toDataURL('image/png');
  const photoEl = document.getElementById('photo');
  photoEl.src = dataUrl;
  photoEl.dataset.custom = 'true';
  document.getElementById('photoName').innerText = 'Camera capture snapshot';

  closeCameraModal();
}

// Tab Switching
function switchView(viewName) {
  activeView = viewName;
  document.querySelectorAll('.nav-tab').forEach((tab) => tab.classList.remove('active'));
  document.querySelectorAll('.view-section').forEach((sec) => sec.classList.remove('active'));

  if (viewName === 'dashboard') {
    document.getElementById('tabDashboard').classList.add('active');
    document.getElementById('viewDashboard').classList.add('active');
    loadDashboardStats();
  } else if (viewName === 'studio') {
    document.getElementById('tabStudio').classList.add('active');
    document.getElementById('viewStudio').classList.add('active');
  } else if (viewName === 'registry') {
    document.getElementById('tabRegistry').classList.add('active');
    document.getElementById('viewRegistry').classList.add('active');
    fetchFilteredFarmers();
  }
}

// API Integration & Dashboard Loader
async function loadDashboardStats() {
  try {
    const res = await fetch('/api/stats');
    if (!res.ok) throw new Error('Failed to fetch stats');
    const data = await res.json();
    renderDashboard(data.stats);
  } catch (err) {
    console.error('Error loading stats:', err);
  }
}

function renderDashboard(stats) {
  if (!stats) return;

  // KPI Cards
  document.getElementById('statTotalFarmers').innerText = stats.totalFarmers || 0;
  document.getElementById('statActiveFarmers').innerText = stats.activeFarmers || 0;
  document.getElementById('statInactiveFarmers').innerText = stats.inactiveFarmers || 0;
  document.getElementById('statTotalVillages').innerText = stats.totalVillages || 0;
  document.getElementById('statTotalArea').innerText = (stats.totalAreaHectare || 0).toFixed(2);
  document.getElementById('statAvgArea').innerText = (stats.avgAreaHectare || 0).toFixed(2);
  document.getElementById('bannerTotalLand').innerText = `${(stats.totalAreaHectare || 0).toFixed(2)} Hectares`;
  document.getElementById('bannerAvgLand').innerText = `${(stats.avgAreaHectare || 0).toFixed(2)} Ha / Farmer`;

  const verificationRate = stats.totalFarmers > 0
    ? Math.round((stats.activeFarmers / stats.totalFarmers) * 100)
    : 100;
  document.getElementById('statVerificationRate').innerText = `${verificationRate}%`;

  // Update Nav Badge
  const navBadge = document.getElementById('navFarmerCount');
  if (navBadge) navBadge.innerText = stats.totalFarmers || 0;

  // Village Wise Breakdown
  const villageListEl = document.getElementById('villageStatsList');
  const vTotalBadge = document.getElementById('villageBreakdownTotal');
  if (vTotalBadge) vTotalBadge.innerText = `${stats.totalVillages || 0} Villages`;

  if (stats.villageWise && stats.villageWise.length > 0) {
    villageListEl.innerHTML = stats.villageWise.map((v) => `
      <div class="village-bar-item">
        <div class="vbar-info">
          <div class="vbar-name-wrap">
            <span class="vbar-name">🏡 ${escapeHtml(v.village)}</span>
            <span class="vbar-area-tag">${v.totalArea} Ha</span>
          </div>
          <div class="vbar-count-wrap">
            <strong>${v.count}</strong>
            <span class="text-muted">(${v.percentage}%)</span>
          </div>
        </div>
        <div class="vbar-track">
          <div class="vbar-fill" style="width: ${Math.max(5, v.percentage)}%"></div>
        </div>
      </div>
    `).join('');
  } else {
    villageListEl.innerHTML = '<div class="empty-state-sm">No village records found. Register farmers to see analytics.</div>';
  }

  // Land Distribution
  const dist = stats.landDistribution || { marginal: 0, small: 0, semiMedium: 0, large: 0 };
  const distTotal = (dist.marginal + dist.small + dist.semiMedium + dist.large) || 1;

  document.getElementById('countMarginal').innerText = `${dist.marginal} farmers (${Math.round((dist.marginal / distTotal) * 100)}%)`;
  document.getElementById('countSmall').innerText = `${dist.small} farmers (${Math.round((dist.small / distTotal) * 100)}%)`;
  document.getElementById('countSemiMedium').innerText = `${dist.semiMedium} farmers (${Math.round((dist.semiMedium / distTotal) * 100)}%)`;
  document.getElementById('countLarge').innerText = `${dist.large} farmers (${Math.round((dist.large / distTotal) * 100)}%)`;

  document.getElementById('barMarginal').style.width = `${Math.round((dist.marginal / distTotal) * 100)}%`;
  document.getElementById('barSmall').style.width = `${Math.round((dist.small / distTotal) * 100)}%`;
  document.getElementById('barSemiMedium').style.width = `${Math.round((dist.semiMedium / distTotal) * 100)}%`;
  document.getElementById('barLarge').style.width = `${Math.round((dist.large / distTotal) * 100)}%`;

  // Recent Registrations Table
  renderRecentRegistrations(stats.recentFarmers || []);
}

function renderRecentRegistrations(recentList) {
  const tbody = document.getElementById('recentFarmersTableBody');
  if (!tbody) return;

  if (!recentList || recentList.length === 0) {
    tbody.innerHTML = '<tr><td colspan="8" class="text-center py-4 text-muted">No recent registrations.</td></tr>';
    return;
  }

  tbody.innerHTML = recentList.map((f) => `
    <tr>
      <td><span class="card-id-pill">${escapeHtml(f.cardNumber)}</span></td>
      <td>
        <div class="farmer-cell">
          <img src="${f.photo || defaultPhotoSrc}" class="avatar-sm" onerror="this.src='${defaultPhotoSrc}'" />
          <div>
            <strong>${escapeHtml(f.farmerName)}</strong>
            <div class="text-xs text-muted">${escapeHtml(f.farmerNameMr || '')}</div>
          </div>
        </div>
      </td>
      <td>${escapeHtml(f.fatherName || '-')}</td>
      <td>${escapeHtml(f.village || '-')}</td>
      <td>${escapeHtml(f.survey || '-')}${f.subSurvey ? '/' + escapeHtml(f.subSurvey) : ''}</td>
      <td><span class="area-badge">${f.area ? f.area + ' Ha' : '-'}</span></td>
      <td>
        <span class="status-pill status-${f.status === 'inactive' ? 'inactive' : 'active'}">
          ${f.status === 'inactive' ? '⏳ Pending' : '✅ Active'}
        </span>
      </td>
      <td>
        <div class="action-btn-group">
          <button class="btn-action-icon" title="Load & View Card" onclick="loadFarmerIntoStudio('${f.id}')">🪪 View</button>
          <a href="/verify.html?id=${encodeURIComponent(f.cardNumber)}" target="_blank" class="btn-action-icon" title="Verify Online">🔍 Verify</a>
        </div>
      </td>
    </tr>
  `).join('');
}

// ----------------------------------------------------
// ADVANCED SEARCH, FILTER, SORT & PAGINATION
// ----------------------------------------------------

async function fetchFilteredFarmers() {
  try {
    const params = new URLSearchParams({
      search: filterState.search,
      village: filterState.village,
      status: filterState.status,
      sortBy: filterState.sortBy,
      sortOrder: filterState.sortOrder,
      page: filterState.page,
      limit: filterState.limit
    });

    const res = await fetch(`/api/farmers?${params.toString()}`);
    if (!res.ok) throw new Error('Failed to load farmers');
    const data = await res.json();

    savedFarmers = data.farmers || [];
    filterState.totalRecords = data.total || 0;
    filterState.totalPages = data.totalPages || 1;
    filterState.page = data.page || 1;
    if (data.villages) {
      filterState.availableVillages = data.villages;
      updateVillageFilterDropdown(data.villages);
    }

    renderRegistry();
    renderActiveFilterChips();
    renderPagination();
  } catch (err) {
    console.error('Error fetching farmers:', err);
  }
}

function handleSearchInput(val) {
  clearTimeout(searchDebounceTimer);
  const clearBtn = document.getElementById('searchClearBtn');
  if (clearBtn) clearBtn.style.display = val ? 'block' : 'none';

  searchDebounceTimer = setTimeout(() => {
    filterState.search = val.trim();
    filterState.page = 1;
    fetchFilteredFarmers();
  }, 300);
}

function clearSearchInput() {
  const searchInput = document.getElementById('farmerSearch');
  if (searchInput) searchInput.value = '';
  const clearBtn = document.getElementById('searchClearBtn');
  if (clearBtn) clearBtn.style.display = 'none';

  filterState.search = '';
  filterState.page = 1;
  fetchFilteredFarmers();
}

function handleVillageFilter(villageVal) {
  filterState.village = villageVal;
  filterState.page = 1;
  fetchFilteredFarmers();
}

function handleStatusFilter(statusVal) {
  filterState.status = statusVal;
  filterState.page = 1;
  fetchFilteredFarmers();
}

function handleSortChange(sortVal) {
  const [sortBy, sortOrder] = sortVal.split('_');
  filterState.sortBy = sortBy;
  filterState.sortOrder = sortOrder || 'desc';
  filterState.page = 1;
  fetchFilteredFarmers();
}

function toggleTableSort(field) {
  if (filterState.sortBy === field) {
    filterState.sortOrder = filterState.sortOrder === 'asc' ? 'desc' : 'asc';
  } else {
    filterState.sortBy = field;
    filterState.sortOrder = 'asc';
  }
  const sortSelector = document.getElementById('sortSelector');
  if (sortSelector) {
    const targetVal = `${filterState.sortBy}_${filterState.sortOrder}`;
    for (let opt of sortSelector.options) {
      if (opt.value === targetVal) {
        sortSelector.value = targetVal;
        break;
      }
    }
  }
  fetchFilteredFarmers();
}

function handlePageSizeChange(limitVal) {
  filterState.limit = parseInt(limitVal, 10) || 10;
  filterState.page = 1;
  fetchFilteredFarmers();
}

function setPage(pageNum) {
  if (pageNum < 1 || pageNum > filterState.totalPages) return;
  filterState.page = pageNum;
  fetchFilteredFarmers();
}

function setRegistryViewMode(mode) {
  filterState.viewMode = mode;
  const gridBtn = document.getElementById('viewModeGridBtn');
  const tableBtn = document.getElementById('viewModeTableBtn');
  const gridContainer = document.getElementById('farmerList');
  const tableWrapper = document.getElementById('farmerTableWrapper');

  if (mode === 'table') {
    gridBtn.classList.remove('active');
    tableBtn.classList.add('active');
    gridContainer.style.display = 'none';
    tableWrapper.style.display = 'block';
  } else {
    tableBtn.classList.remove('active');
    gridBtn.classList.add('active');
    tableWrapper.style.display = 'none';
    gridContainer.style.display = 'grid';
  }
}

function updateVillageFilterDropdown(villages) {
  const select = document.getElementById('filterVillage');
  if (!select) return;

  const currentSelection = filterState.village;
  const options = ['<option value="all">🏘️ All Villages</option>'];

  villages.forEach((v) => {
    const isSelected = v.toLowerCase() === currentSelection.toLowerCase() ? 'selected' : '';
    options.push(`<option value="${escapeHtml(v)}" ${isSelected}>${escapeHtml(v)}</option>`);
  });

  select.innerHTML = options.join('');
}

function renderActiveFilterChips() {
  const container = document.getElementById('activeFilterChips');
  if (!container) return;

  const chips = [];

  if (filterState.search) {
    chips.push(`
      <span class="filter-chip">
        Search: "${escapeHtml(filterState.search)}"
        <button onclick="clearSearchInput()" title="Remove search">✕</button>
      </span>
    `);
  }

  if (filterState.village && filterState.village !== 'all') {
    chips.push(`
      <span class="filter-chip">
        Village: ${escapeHtml(filterState.village)}
        <button onclick="handleVillageFilter('all')" title="Clear village filter">✕</button>
      </span>
    `);
  }

  if (filterState.status && filterState.status !== 'all') {
    chips.push(`
      <span class="filter-chip">
        Status: ${filterState.status}
        <button onclick="handleStatusFilter('all')" title="Clear status filter">✕</button>
      </span>
    `);
  }

  if (chips.length > 0) {
    chips.push(`
      <button class="btn-clear-all-chips" onclick="resetAllFilters()">
        Reset All Filters
      </button>
    `);
    container.innerHTML = chips.join('');
    container.style.display = 'flex';
  } else {
    container.innerHTML = '';
    container.style.display = 'none';
  }
}

function resetAllFilters() {
  filterState.search = '';
  filterState.village = 'all';
  filterState.status = 'all';
  filterState.sortBy = 'createdAt';
  filterState.sortOrder = 'desc';
  filterState.page = 1;

  document.getElementById('farmerSearch').value = '';
  document.getElementById('filterVillage').value = 'all';
  document.getElementById('filterStatus').value = 'all';
  document.getElementById('sortSelector').value = 'createdAt_desc';
  document.getElementById('searchClearBtn').style.display = 'none';

  fetchFilteredFarmers();
}

function renderRegistry() {
  const countEl = document.getElementById('farmerCount');
  const navBadge = document.getElementById('navFarmerCount');

  const total = filterState.totalRecords;
  if (countEl) countEl.innerText = `${total} registered farmer${total === 1 ? '' : 's'}`;
  if (navBadge) navBadge.innerText = total;

  if (filterState.viewMode === 'table') {
    renderRegistryTable();
  } else {
    renderRegistryGrid();
  }
}

function renderRegistryGrid() {
  const container = document.getElementById('farmerList');
  if (!container) return;

  if (!savedFarmers || savedFarmers.length === 0) {
    container.innerHTML = `
      <div class="empty-state-card">
        <span class="empty-icon">🔍</span>
        <h4>No matching farmers found</h4>
        <p>Try adjusting your search keywords, clearing village or status filters.</p>
        <button class="btn btn-sm btn-outline mt-2" onclick="resetAllFilters()">Reset Filters</button>
      </div>
    `;
    return;
  }

  container.innerHTML = savedFarmers.map((f) => `
    <div class="saved-item-card">
      <div class="saved-card-top">
        <div class="farmer-avatar-wrap">
          <img src="${f.photo || defaultPhotoSrc}" class="saved-avatar" onerror="this.src='${defaultPhotoSrc}'" />
          <span class="status-indicator-dot ${f.status === 'inactive' ? 'dot-inactive' : 'dot-active'}" title="${f.status}"></span>
        </div>
        <div class="saved-title-info">
          <div class="saved-card-badge">${escapeHtml(f.cardNumber)}</div>
          <h4 class="farmer-title">${escapeHtml(f.farmerName)}</h4>
          <div class="farmer-title-mr">${escapeHtml(f.farmerNameMr || '')}</div>
        </div>
      </div>

      <div class="saved-card-details">
        <div class="detail-row">
          <span class="d-label">Father:</span>
          <span class="d-val">${escapeHtml(f.fatherName || '-')}</span>
        </div>
        <div class="detail-row">
          <span class="d-label">Village:</span>
          <span class="d-val font-semibold">${escapeHtml(f.village || '-')}</span>
        </div>
        <div class="detail-row">
          <span class="d-label">Survey:</span>
          <span class="d-val">${escapeHtml(f.survey || '-')}${f.subSurvey ? '/' + escapeHtml(f.subSurvey) : ''}</span>
        </div>
        <div class="detail-row">
          <span class="d-label">Land Area:</span>
          <span class="d-val text-green font-semibold">${f.area ? f.area + ' Hectare' : '-'}</span>
        </div>
        <div class="detail-row">
          <span class="d-label">Aadhaar:</span>
          <span class="d-val">${f.aadhaar ? maskAadhaar(f.aadhaar) : '-'}</span>
        </div>
      </div>

      <div class="saved-card-actions">
        <button class="btn-card-action btn-primary-soft" onclick="loadFarmerIntoStudio('${f.id}')" title="Load into Studio">
          🪪 Card
        </button>
        <a href="/verify.html?id=${encodeURIComponent(f.cardNumber)}" target="_blank" class="btn-card-action btn-verify-soft" title="Verify Online Portal">
          🔍 Verify
        </a>
        <button class="btn-card-action btn-danger-soft" onclick="deleteFarmerRecord('${f.id}')" title="Delete Farmer">
          🗑️
        </button>
      </div>
    </div>
  `).join('');
}

function renderRegistryTable() {
  const tbody = document.getElementById('farmerTableBody');
  if (!tbody) return;

  if (!savedFarmers || savedFarmers.length === 0) {
    tbody.innerHTML = '<tr><td colspan="9" class="text-center py-5 text-muted">No records match your search criteria.</td></tr>';
    return;
  }

  tbody.innerHTML = savedFarmers.map((f) => `
    <tr>
      <td><span class="card-id-pill">${escapeHtml(f.cardNumber)}</span></td>
      <td>
        <div class="farmer-cell">
          <img src="${f.photo || defaultPhotoSrc}" class="avatar-sm" onerror="this.src='${defaultPhotoSrc}'" />
          <div>
            <strong>${escapeHtml(f.farmerName)}</strong>
            <div class="text-xs text-muted">${escapeHtml(f.farmerNameMr || '')}</div>
          </div>
        </div>
      </td>
      <td>${escapeHtml(f.fatherName || '-')}</td>
      <td><strong>${escapeHtml(f.village || '-')}</strong></td>
      <td>${escapeHtml(f.survey || '-')}${f.subSurvey ? '/' + escapeHtml(f.subSurvey) : ''}</td>
      <td><span class="area-badge">${f.area ? f.area + ' Ha' : '-'}</span></td>
      <td class="font-mono text-sm">${f.aadhaar ? maskAadhaar(f.aadhaar) : '-'}</td>
      <td>
        <span class="status-pill status-${f.status === 'inactive' ? 'inactive' : 'active'}">
          ${f.status === 'inactive' ? '⏳ Pending' : '✅ Active'}
        </span>
      </td>
      <td>
        <div class="action-btn-group">
          <button class="btn-action-icon" title="View Card" onclick="loadFarmerIntoStudio('${f.id}')">🪪</button>
          <a href="/verify.html?id=${encodeURIComponent(f.cardNumber)}" target="_blank" class="btn-action-icon" title="Verify Online">🔍</a>
          <button class="btn-action-icon btn-del" title="Delete" onclick="deleteFarmerRecord('${f.id}')">🗑️</button>
        </div>
      </td>
    </tr>
  `).join('');
}

function renderPagination() {
  const infoEl = document.getElementById('paginationInfo');
  const controlsEl = document.getElementById('paginationControls');
  if (!infoEl || !controlsEl) return;

  const total = filterState.totalRecords;
  const page = filterState.page;
  const limit = filterState.limit;
  const totalPages = filterState.totalPages;

  if (total === 0) {
    infoEl.innerText = 'Showing 0 to 0 of 0 records';
    controlsEl.innerHTML = '';
    return;
  }

  const start = (page - 1) * limit + 1;
  const end = Math.min(page * limit, total);
  infoEl.innerText = `Showing ${start} to ${end} of ${total} records (Page ${page} of ${totalPages})`;

  const btns = [];

  // Prev Button
  btns.push(`
    <button class="page-btn" ${page <= 1 ? 'disabled' : ''} onclick="setPage(${page - 1})">
      « Prev
    </button>
  `);

  // Numeric page buttons
  const maxButtons = 5;
  let startPage = Math.max(1, page - Math.floor(maxButtons / 2));
  let endPage = Math.min(totalPages, startPage + maxButtons - 1);

  if (endPage - startPage + 1 < maxButtons) {
    startPage = Math.max(1, endPage - maxButtons + 1);
  }

  if (startPage > 1) {
    btns.push(`<button class="page-btn" onclick="setPage(1)">1</button>`);
    if (startPage > 2) btns.push(`<span class="page-ellipsis">...</span>`);
  }

  for (let p = startPage; p <= endPage; p++) {
    btns.push(`
      <button class="page-btn ${p === page ? 'active' : ''}" onclick="setPage(${p})">
        ${p}
      </button>
    `);
  }

  if (endPage < totalPages) {
    if (endPage < totalPages - 1) btns.push(`<span class="page-ellipsis">...</span>`);
    btns.push(`<button class="page-btn" onclick="setPage(${totalPages})">${totalPages}</button>`);
  }

  // Next Button
  btns.push(`
    <button class="page-btn" ${page >= totalPages ? 'disabled' : ''} onclick="setPage(${page + 1})">
      Next »
    </button>
  `);

  controlsEl.innerHTML = btns.join('');
}

// ----------------------------------------------------
// FORM ACTIONS & CARD OPERATIONS
// ----------------------------------------------------

function loadFarmerIntoStudio(farmerId) {
  const f = savedFarmers.find((entry) => String(entry.id) === String(farmerId));
  if (!f) {
    fetch(`/api/farmers/${farmerId}`)
      .then((res) => res.json())
      .then((data) => {
        if (data.farmer) populateStudioWithFarmer(data.farmer);
      });
    return;
  }
  populateStudioWithFarmer(f);
}

function populateStudioWithFarmer(f) {
  document.getElementById('cardInput').value = f.cardNumber || '';
  document.getElementById('nameInput').value = f.farmerName || '';
  document.getElementById('nameMrInput').value = f.farmerNameMr || '';
  document.getElementById('fatherInput').value = f.fatherName || '';
  document.getElementById('fatherMrInput').value = f.fatherNameMr || '';
  document.getElementById('addressInput').value = f.address || '';
  document.getElementById('villageInput').value = f.village || '';
  document.getElementById('surveyInput').value = f.survey || '';
  document.getElementById('subSurveyInput').value = f.subSurvey || '';
  document.getElementById('areaInput').value = f.area || '';
  document.getElementById('aadhaarInput').value = f.aadhaar || '';

  // Update Live Card
  document.getElementById('fid').innerText = f.cardNumber || 'KC-1001';
  document.getElementById('name_en').innerText = f.farmerName || 'Example Name';
  document.getElementById('name_mr').innerText = f.farmerNameMr || 'उदा. रमेश पाटील';
  document.getElementById('father_en').innerText = f.fatherName || 'Example Name';
  document.getElementById('father_mr').innerText = f.fatherNameMr || 'उदा. सुरेश पाटील';
  document.getElementById('address').innerText = f.address || 'ABC Street';
  document.getElementById('village').innerText = f.village || 'Takarkheda';
  document.getElementById('survey').innerText = f.survey || '213';
  document.getElementById('sub').innerText = f.subSurvey || '2';
  document.getElementById('area').innerText = f.area || '1.08';

  const photoEl = document.getElementById('photo');
  if (f.photo) {
    photoEl.src = f.photo;
    photoEl.dataset.custom = 'true';
    document.getElementById('photoName').innerText = 'Loaded profile image';
  } else {
    resetPhoto();
  }

  setID(f.cardNumber || 'KC-1001');
  toggleAadhaarMask();

  switchView('studio');
}

async function saveFarmer() {
  const name = document.getElementById('nameInput').value.trim();
  const father = document.getElementById('fatherInput').value.trim();
  const address = document.getElementById('addressInput').value.trim();
  const village = document.getElementById('villageInput').value.trim();

  const errors = [];
  if (!name) errors.push('Farmer Name is required.');
  if (!father) errors.push("Father's Name is required.");
  if (!address) errors.push('Address is required.');
  if (!village) errors.push('Village is required.');

  const errBox = document.getElementById('validationErrors');
  if (errors.length > 0) {
    errBox.innerHTML = errors.map((e) => `<p class="error-text">⚠️ ${e}</p>`).join('');
    return;
  }
  errBox.innerHTML = '';

  const photoEl = document.getElementById('photo');
  const photo = photoEl.dataset.custom === 'true' ? photoEl.src : '';

  const payload = {
    cardNumber: document.getElementById('cardInput').value.trim(),
    farmerName: name,
    farmerNameMr: document.getElementById('nameMrInput').value.trim(),
    fatherName: father,
    fatherNameMr: document.getElementById('fatherMrInput').value.trim(),
    address,
    village,
    survey: document.getElementById('surveyInput').value.trim(),
    subSurvey: document.getElementById('subSurveyInput').value.trim(),
    area: document.getElementById('areaInput').value.trim(),
    aadhaar: document.getElementById('aadhaarInput').value.trim(),
    status: 'active',
    photo
  };

  try {
    const res = await fetch('/api/farmers', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    if (!res.ok) {
      const errData = await res.json();
      throw new Error(errData.errors ? errData.errors.join(', ') : 'Failed to save');
    }

    alert('✅ Farmer card saved successfully!');
    loadDashboardStats();
    fetchFilteredFarmers();
  } catch (err) {
    alert('Error saving farmer: ' + err.message);
  }
}

async function deleteFarmerRecord(id) {
  if (!confirm('Are you sure you want to delete this farmer registration?')) return;

  try {
    const res = await fetch(`/api/farmers/${id}`, { method: 'DELETE' });
    if (!res.ok) throw new Error('Failed to delete');

    loadDashboardStats();
    fetchFilteredFarmers();
  } catch (err) {
    alert('Error deleting record: ' + err.message);
  }
}

function clearForm() {
  document.getElementById('cardInput').value = '';
  document.getElementById('nameInput').value = '';
  document.getElementById('nameMrInput').value = '';
  document.getElementById('fatherInput').value = '';
  document.getElementById('fatherMrInput').value = '';
  document.getElementById('addressInput').value = '';
  document.getElementById('villageInput').value = '';
  document.getElementById('surveyInput').value = '';
  document.getElementById('subSurveyInput').value = '';
  document.getElementById('areaInput').value = '';
  document.getElementById('aadhaarInput').value = '';

  document.getElementById('name_en').innerText = 'Example Name';
  document.getElementById('name_mr').innerText = 'उदा. रमेश पाटील';
  document.getElementById('father_en').innerText = 'Example Name';
  document.getElementById('father_mr').innerText = 'उदा. सुरेश पाटील';
  document.getElementById('address').innerText = 'ABC Street';
  document.getElementById('village').innerText = 'Takarkheda';
  document.getElementById('survey').innerText = '213';
  document.getElementById('sub').innerText = '2';
  document.getElementById('area').innerText = '1.08';
  document.getElementById('fid').innerText = 'KC-1001';

  resetPhoto();
  setID('KC-1001');
  toggleAadhaarMask();
  const errBox = document.getElementById('validationErrors');
  if (errBox) errBox.innerHTML = '';
}

function exportCSV() {
  const params = new URLSearchParams({
    search: filterState.search,
    village: filterState.village,
    status: filterState.status
  });
  window.location.href = `/api/farmers/export/csv?${params.toString()}`;
}

// PDF Export Handlers
async function handleDownloadCombined() {
  const btn = document.getElementById('downloadCombinedBtn');
  const origText = btn.innerText;
  btn.innerText = 'Generating PDF...';

  try {
    const { jsPDF } = window.jspdf;
    const cardFront = document.getElementById('card');
    const cardBack = document.getElementById('cardBack');

    const canvasFront = await html2canvas(cardFront, { scale: 3, useCORS: true });
    const canvasBack = await html2canvas(cardBack, { scale: 3, useCORS: true });

    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgDataFront = canvasFront.toDataURL('image/png');
    const imgDataBack = canvasBack.toDataURL('image/png');

    // Place Front Card
    pdf.addImage(imgDataFront, 'PNG', 20, 20, 170, 100);
    // Place Back Card
    pdf.addImage(imgDataBack, 'PNG', 20, 130, 170, 100);

    const cardId = document.getElementById('fid').innerText || 'KC-1001';
    pdf.save(`Kisan_Card_Dual_${cardId}.pdf`);
  } catch (err) {
    alert('PDF Generation failed: ' + err.message);
  } finally {
    btn.innerText = origText;
  }
}

async function handleDownload() {
  const cardFront = document.getElementById('card');
  const canvas = await html2canvas(cardFront, { scale: 3, useCORS: true });
  const { jsPDF } = window.jspdf;
  const pdf = new jsPDF('l', 'mm', [85.6, 53.98]);
  pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0, 85.6, 53.98);
  pdf.save('Kisan_Card_Front.pdf');
}

async function handleDownloadBack() {
  const cardBack = document.getElementById('cardBack');
  const canvas = await html2canvas(cardBack, { scale: 3, useCORS: true });
  const { jsPDF } = window.jspdf;
  const pdf = new jsPDF('l', 'mm', [85.6, 53.98]);
  pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0, 85.6, 53.98);
  pdf.save('Kisan_Card_Back.pdf');
}

function handlePrint() {
  window.print();
}

function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

// Initial Boot
document.addEventListener('DOMContentLoaded', () => {
  loadDashboardStats();
  fetchFilteredFarmers();
  setID(document.getElementById('cardInput').value || 'KC-1001');
});
